tap "modular/packages", "https://github.com/modular/homebrew-packages.git", trusted: true
tap "ubuntu/microk8s", trusted: true
# Microsoft Azure CLI 2.0
brew "azure-cli"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Isolated development environments using Docker
brew "docker-compose"
# GitHub command-line tool
brew "gh"
# Git extension for versioning large files
brew "git-lfs"
# Kubernetes package manager
brew "helm"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Interactive environments for writing and running code
brew "jupyterlab"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Modern shell for the GitHub era
brew "nushell"
# Drop-in replacement for Terraform. Infrastructure as Code Tool
brew "opentofu"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Terminal multiplexer
brew "tmux"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Pluggable terminal workspace, with terminal multiplexer as the base feature
brew "zellij"
# UNIX shell (command interpreter)
brew "zsh"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Modular developer CLI tool
brew "modular/packages/modular"
cask "font-geist-mono-nerd-font"
cask "font-hack-nerd-font"
# Orchestrates virtual Ubuntu instances
cask "multipass"
# Open-source version of the X.Org X Window System
cask "xquartz"
vscode "akamud.vscode-theme-onedark"
vscode "akamud.vscode-theme-onelight"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "angular.ng-template"
vscode "anysphere.cursorpyright"
vscode "anysphere.remote-containers"
vscode "anysphere.remote-ssh"
vscode "anysphere.remote-wsl"
vscode "arcticicestudio.nord-visual-studio-code"
vscode "azemoh.one-monokai"
vscode "batisteo.vscode-django"
vscode "bradlc.vscode-tailwindcss"
vscode "charliermarsh.ruff"
vscode "christian-kohler.path-intellisense"
vscode "cschlosser.doxdocgen"
vscode "eamodio.gitlens"
vscode "equinusocio.vsc-community-material-theme"
vscode "equinusocio.vsc-material-theme"
vscode "equinusocio.vsc-material-theme-icons"
vscode "esbenp.prettier-vscode"
vscode "evidence.evidence-vscode"
vscode "evidence.sqltools-duckdb-driver"
vscode "fastapilabs.fastapi-vscode"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "grapecity.gc-excelviewer"
vscode "gruntfuggly.todo-tree"
vscode "ing-bank.vscode-psl"
vscode "jeff-hykin.better-cpp-syntax"
vscode "johnpapa.angular2"
vscode "johnpapa.winteriscoming"
vscode "kelvin.vscode-sshfs"
vscode "leighlondon.eml"
vscode "leonardssh.vscord"
vscode "mechatroner.rainbow-csv"
vscode "modular-mojotools.vscode-mojo"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-ossdata.vscode-postgresql"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vsliveshare.vsliveshare"
vscode "mthierman.theme-flexoki"
vscode "mtxr.sqltools"
vscode "octref.vetur"
vscode "openai.chatgpt"
vscode "pkief.material-icon-theme"
vscode "raillyhugo.one-hunter"
vscode "redhat.java"
vscode "redhat.vscode-commons"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "reditorsupport.r"
vscode "reditorsupport.r-syntax"
vscode "samuelcolvin.jinjahtml"
vscode "svelte.svelte-vscode"
vscode "tomoki1207.pdf"
vscode "twxs.cmake"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscodevim.vim"
vscode "vue.volar"
vscode "zhuangtongfa.material-theme"
go "github.com/spf13/cobra-cli"
go "github.com/go-delve/delve/cmd/dlv"
go "github.com/ramya-rao-a/go-outline"
go "golang.org/x/tools/cmd/goimports"
go "github.com/fatih/gomodifytags"
go "github.com/uudashr/gopkgs/v2/cmd/gopkgs"
go "github.com/haya14busa/goplay/cmd/goplay"
go "golang.org/x/tools/gopls"
go "github.com/cweill/gotests/gotests"
go "github.com/josharian/impl"
go "sigs.k8s.io/kind"
go "honnef.co/go/tools/cmd/staticcheck"
npm "@angular/cli"
npm "@ionic/cli"
npm "@nebular/theme"
npm "cordova-res"
npm "native-run"
npm "openclaw"
